#!/bin/bash
set -euo pipefail

BUILD_DIR=${SRC_DIR}/build
ITK_CMAKE_DEST="${PREFIX}/lib/cmake/ITK-6.0"
WRAP_CMAKE_DEST="${PREFIX}/lib/cmake/Wrapping"
TYPEDEFS_DEST="${PREFIX}/lib/cmake/ITK-6.0/Wrapping/Typedefs"
INCLUDE_DEST="${PREFIX}/include/ITK-6.0"

mkdir -p "${ITK_CMAKE_DEST}"
mkdir -p "${WRAP_CMAKE_DEST}"

# Wrapping CMake helpers that ITKModuleExternal.cmake includes by name.
cp "${SRC_DIR}/CMake/WrappingConfigCommon.cmake" "${ITK_CMAKE_DEST}/WrappingConfigCommon.cmake"
cp "${SRC_DIR}/CMake/ITKSetPython3Vars.cmake"     "${ITK_CMAKE_DEST}/ITKSetPython3Vars.cmake"

# Full Wrapping/ source tree. ITKModuleExternal.cmake:258 sets
# WRAP_ITK_CMAKE_DIR = ${ITK_CMAKE_DIR}/../Wrapping, which resolves to this
# location given ITK_CMAKE_DIR = ${PREFIX}/lib/cmake/ITK-6.0/.
cp -R "${SRC_DIR}/Wrapping/." "${WRAP_CMAKE_DEST}/"

# Per-module wrapping/ subdirs (Modules/<Group>/<Module>/wrapping/) so that
# external builds re-using ITK module sources can resolve .wrap dependencies.
cd "${SRC_DIR}"
while IFS= read -r wrap_src; do
    rel="${wrap_src#./}"           # e.g. Modules/Core/Common/wrapping
    dest="${INCLUDE_DEST}/${rel}"
    mkdir -p "${dest}"
    cp -R "${wrap_src}/." "${dest}/"
done < <(find Modules -type d -name wrapping)

# Wrapping build artifacts generated by ITK's wrapping pass into
# ${BUILD_DIR}/Wrapping/Typedefs/: per-module .i / .idx / .mdx files plus
# pyBase.i and the python/ subdir of *_ext.i files. ITK upstream does NOT
# install these, but downstream wrapping (SWIG -I path) requires them at
# ${ITK_CMAKE_DIR}/Wrapping/Typedefs/. Copy them in here so consumer
# remote-module builds can resolve %import "pyBase.i" and dependency .mdx
# lookups.
mkdir -p "${TYPEDEFS_DEST}"
cp -R "${BUILD_DIR}/Wrapping/Typedefs/." "${TYPEDEFS_DEST}/"
